### ISSUE TITLE
No Korean in battle.net

### ISSUE THREAD

**Issue by rsanden** [awesie/wine-starcraft#3]
In Battle.net, most Asia server games use Korean, and Korean text isn't showing up.

I tried "`winetricks baekmuk`", which installed successfully, but it made no difference. I know that SC 1.18 brings UTF-8 support, but I'm unsure if it's just a different missing font or a wine-related problem.

[This is my installation](https://gist.github.com/rsanden/e793c46e7d022686bf089ae92bed58ec) under Ubuntu 16.04.

**Comment by awesie** [comment]
StarCraft uses the Arial Unicode MS font. You should use `winetricks unifont` which will install a replacement font and an alias so Starcraft loads it.

I confirmed that this fixed the issue both in the lobby and in-game.

**Comment by rsanden** [comment]
That does indeed fix it. Thank you so much for everything you've done!
